# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  AllowedPatterns:
    - "# renovate: .*"

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
