# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  AllowedPatterns:
    - "# renovate: .*"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
