name: "Lint with KICS"
description: "Run KICS IaC security scanner"

runs:
  using: "composite"
  steps:
    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v2
      with:
        path: "."
        fail_on: high,medium
        output_formats: "json,sarif"
