name: "GitHub App Authentication"
description: "Authenticate as a GitHub App and configure git user settings"

branding:
  icon: "lock"
  color: "blue"

inputs:
  app-id:
    description: "GitHub App ID"
    required: true

  private-key:
    description: "GitHub App private key"
    required: true

  owner:
    description: "Repository owner (defaults to current repository owner)"
    required: false
    default: ${{ github.repository_owner }}

outputs:
  token:
    description: "GitHub App token"
    value: ${{ steps.app-token.outputs.token }}

  app-slug:
    description: "GitHub App slug name"
    value: ${{ steps.app-token.outputs.app-slug }}

  user-id:
    description: "GitHub App bot user ID"
    value: ${{ steps.get-user-id.outputs.user-id }}

  user-name:
    description: "GitHub App bot user name (app slug with [bot] suffix)"
    value: ${{ steps.get-user-id.outputs.user-name }}

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ inputs.owner }}

    - name: Get GitHub App User ID
      id: get-user-id
      shell: bash
      run: |
        echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        echo "user-name=${{ steps.app-token.outputs.app-slug }}[bot]" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Configure git
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        gh auth setup-git
        echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
        git config --global user.name '${{ steps.get-user-id.outputs.user-name }}'
        git config user.name '${{ steps.get-user-id.outputs.user-name }}'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.get-user-id.outputs.user-name }}@users.noreply.github.com'
        git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.get-user-id.outputs.user-name }}@users.noreply.github.com'

    - name: Configure repo checkout token
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        token: ${{ steps.app-token.outputs.token }}
        clean: false
        persist-credentials: true
