name: "Lint with Grype"
description: "Run grype vulnerability scanner"

runs:
  using: "composite"
  steps:
    - name: Cache Grype vulnerability DB
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: /home/runner/.cache/grype/db/
        key: grype-db

    - name: Check if DB needs updates
      shell: bash
      env:
        GRYPE_DB_CACHE_DIR: /home/runner/.cache/grype/db/
      run: |
        echo "Checking for Grype DB updates..."
        if ! grype db check; then
          echo "Updating Grype DB..."
          grype db update
        else
          echo "Grype DB is up to date."
        fi

    - name: Run grype
      shell: bash
      env:
        GRYPE_DB_CACHE_DIR: /home/runner/.cache/grype/db/
      run: |
        echo "Running grype..."
        grype dir:.

        grype db status

    - name: debug
      uses: pyTooling/Actions/with-post-step@370c306306304663febee1525552a09e061588fa # v7.4.2
      with:
        main: |
          echo "Grype DB status after scan:"
          grype db status

          echo "cache status"
          find ~/.cache/grype/db/ -type f
          ls -lha ~/.cache/grype/db/**
        post: |
          echo "Grype DB status after scan:"
          grype db status

          echo "cache status"
          find ~/.cache/grype/db/ -type f
          ls -lha ~/.cache/grype/db/**
