name: "Lint with Grype"
description: "Run grype vulnerability scanner"

runs:
  using: "composite"
  steps:
    - name: Cache Grype vulnerability DB
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ~/.cache/grype/db/
        key: grype-db

    - name: Check if DB needs updates
      shell: bash
      env:
        GRYPE_DB_CACHE_DIR: ~/.cache/grype/db/
      run: |
        echo "Checking for Grype DB updates..."
        if ! grype db check; then
          echo "Updating Grype DB..."
          grype db update
        else
          echo "Grype DB is up to date."
        fi

    - name: Run grype
      shell: bash
      env:
        GRYPE_DB_CACHE_DIR: ~/.cache/grype/db/
      run: |
        echo "Running grype..."
        grype dir:.

        grype db status
