name: "Lint with Grype"
description: "Run grype vulnerability scanner"

runs:
  using: "composite"
  steps:
    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        install_args: "grype"

    - name: Run grype
      shell: bash
      run: |
        echo "Running grype..."
        grype dir:.
