name: "Lint with Trivy"
description: "Run trivy vulnerability scanner and generate SBOM"

runs:
  using: "composite"
  steps:
    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        install_args: "trivy"

    - name: Run trivy filesystem scan
      shell: bash
      run: |
        echo "Running trivy filesystem scan..."
        trivy fs . --scanners vuln,secret,misconfig

    - name: Generate trivy SBOM
      shell: bash
      run: |
        echo "Generating trivy SBOM..."
        trivy fs . --format cyclonedx --output trivy-sbom.json

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-sbom
        path: trivy-sbom.json
        retention-days: 30
